### PR TITLE
upgraded to mongoose v6

### PR DESCRIPTION
**Pull request by SEBattestis**
Hi Clayton Gulick,

I recently upgraded my mongoose to v6 in my project.
It seems that your plugin is incompatible with this new version since it involves some breaking changes like execPopulate method which is not available anymore.
You’ll find in my PR  a naive upgrade to ensure v6 compatibility.

Best regards,

SEB

### CODE REVIEW

**Comment by olivierto** [comment]
👍  LGTM

**Comment by claytongulick** [comment]
Thanks for this!

**Comment by SEBattestis** [comment]
Thanks a lot!!
Please, could you deploy the last version?

**Comment by claytongulick** [comment]
@SEBattestis done, thanks again.

**Pull request merged**
